### ISSUE TITLE
3 partitions of the project

### ISSUE THREAD

**Issue by hanabzu** [hanabzu/Warehouse-Management-System#1]
미니 프로젝트 3가지로 나누어야 하는데 어떻게 나눌지 정해야 할 것 같습니다.
먼저 현재 정해진 problem statement의 세 유저인 admin, 창고계정, 지점계정으로 나누는 방법이 있으나 각 계정 별 기능이 겹치는 부분도 있고 분량에 차이가 있습니다.
그래서 예를 들면 유저관리,  트랜잭션/재고관리,  AI모델을 활용한 동향리포트 이 세 파트로 나누는 것도 괜찮을 거 같습니다.
그 외에도 다른 의견 자유롭게 부탁드리겠습니다.

**Comment by Gyong97** [comment]
저도 처음에는 위 처럼 계정별로 나눈다고 단순하게 생각했었는데, 다시 생각해보니 많은 부분에서 겹칠 것 같습니다. 
그래서 최대한 관심사 분리를 이루기 위한 방향으로 3가지 파트를 나누는 것을 고민해봐야 할 것 같습니다. 
5강을 들어보니 분할에 대한 여러가지 이야기가 있던데 Problem Statement에서 requirement를 잘 뽑아서 크게 3가지로 분할 하는 방향으로 가야할 것 같다고 생각합니다!
