### ISSUE TITLE
REQ-transaction 비즈니스 관점에서의 질문 - 김지용님 커멘트 이동

### ISSUE THREAD

**Issue by hanabzu** [hanabzu/Warehouse-Management-System#11]
김지용 - 커밋 질문 코멘트
// 비즈니스 관계자에게 질문.

-사용자 입장을 이렇게 이해하는게 맞을까요?
점주 입장 -> 재고를 최소화 하면서 물품관리.
창고 관리자 입장 -> 창고 공간을 최소화 하면서 물품 관리. <- 크기에 관한 정보 필요하다고 생각

창고는 물품을 받는 입장, 스스로 물품을 발주 신청하는 입장이 아니다. <- 이렇게 이해하는게 맞나요?

어드민 -> REQ-3 : 각 브랜드에 자동 발주(창고로). -> 비용 문제. 물품 계약비는 브랜드에게, 창고 저장비용은 창고 관리자에게(이것은 브랜드->창고로 지불?)
혹은 어드민이 물품 계약은 자체적으로 진행하기 때문에 브랜드에게 계약비 지불은 프로그램으로 필요가 없는 부분이라고 이해하는게 맞나요?

점주 -> 창고로 발주 시, 돈은 어떻게 지불? to 창고? to 어드민?

*******************************************************************************************************************************

한경빈 - 커밋 답변 코멘트
재고를 최소화 하면서 물품관리를 하는 것도 맞는 말이고 유통기한이 있는 식품같은 경우 폐기물이 나오지 않도록 조절하는 것이 중요할 것 같습니다.
관련 항목에 대해 생각해보겠습니다.
창고 공간을 효율적으로 사용해야 하는 것도 맞겠네요 아무래도 물품 데이터에 창고에서의 위치 같은걸 정확히 표현해두는게 좋겠습니다 (도서관에서처럼)

시스템이 물품을 브랜드에 발주 신청합니다! 그런데 저는 그 기능을 자동화로 생각해서 예를 들어 달마다 지점들로 나가는 어떤 상품의 총 개수가 있다면 그만큼+다음달의 변동사항 예측을 통해 자동적으로 발주 신청하고, 받게 된다고 생각했습니다. (창고 관리자는 어디까지나 유저이므로 발주하는 주체는 창고지만 결국 시스템이 한다고 생각)
이 부분은 제가 임의로 정해둔거라 이슈를 통해 확실히 정하는게 좋겠습니다!

또한 비용문제도 역시 위에서 생기는것 같은데요. 그렇다면 기능을 좀 수정하여 시스템은 창고관리자에게 발주하는 물품의 항목과 개수를 추천하고, 창고관리자가 원하는대로 수정하여 (예 추천으로 A물품 : 5000개가 떴다면 +-하여 개수를 수정하는 식) 최종적으로 컨펌을 내리게하는것은 어떨까요?
창고가 물품들을 브랜드에게서 구매한거니까 창고 저장비용은 필요없지않을까요? 창고와 지점을 도매-소매개념으로 보면 될것같습니다.

돈은 계정에 어카운트를 연결해놓고 트랜잭션 영수증에 맞춰서 결제되는 방식으로 하면 될 것 같습니다.

**Comment by Gyong97** [comment]
도매-소매의 개념으로 창고를 본다면 그렇게 보는게 맞는거 같네요. 
창고 공간 효율 이야기는 제가 말했던 것은 창고 관리자의 입장에서 물품을 최대한 많이 넣을 수 있는 방향으로 남은 공간을 최소화 한다는 이야기였는데 ( 창고 관리자 입장이 단순 물품을 보관하고 물품 보관비를 받는 창고주의 역할로 보았을 때.) 도매-소매의 개념으로 보게 된다면 이 사항은 생각을 해봐야 겠네요. 
 물품 데이터를 창고에서의 위치 같은 것으로 표현하는 것은 이 프로그램에서는 필요가 없을 것 같다고 생각합니다. 물품 거래와 판매 동향이 주 목적임을 생각하면 창고에서 물품의 위치 관리는 다른 어플리케이션이 해야 할 역할이라고 생각합니다.
 다만 창고별 정보를 입력할 때 창고의 크기를 입력 받고, 그에 맞춰 최대 수용량 같은 것을 정해 두어야 할지, 그런 것은 프로그램 사용자가 알아서 해야할 부분인지는 생각을 해 보아야 할 것 같습니다.

**Comment by hanabzu** [comment]
넵 그렇네요. 창고 내부에서의 물품 관리는 트랜잭션과는 좀 거리가 있는게 맞네요.
창고의 전체 크기도 생각해보면 기본적으로 매우 크다고 가정하는 것이 보통이므로 굳이 신경 쓰지 않아도 될 것 같습니다.
