### ISSUE TITLE
F/NF에 관하여 (중요)

### ISSUE THREAD

**Issue by hanabzu** [hanabzu/Warehouse-Management-System#12]
차성덕 저의 <소프트웨어 공학 이야기>에서 관련 파트를 읽어보았는데 저희 현재까지 진행한 문서에서 수정할 부분이 있을 것 같아요.
functional requirements와 non-functional requirements를 잘 나누어 작성해야 할 것 같습니다.
비기능적 요구는 기능적 요구에 종속되어서 기능적 요구를 할 때에 필요한 제약사항과 비슷한 의미로 생각하면 좋을 것 같아요.
예를 들어 로봇 청소기소프트웨어라면
NF : 청소 과정의 맵이 저장되어야 한다.
와 같은 예시가 있겠습니다. 

저도 틀렸거나 아직 완벽히 이해하기 어려운 부분도 있으니 관련해서 서로 피드백 나누면서 진행하면 될 것 같습니다!

**Comment by Gyong97** [comment]
https://timewizhan.tistory.com/entry/Software-Requirement-Part-2

여기도 기능적/비기능적 요구에 대해 짧게 잘 설명해 주고 있는 것 같아서 공유합니다!
