### ISSUE TITLE
Problem-Statement 수정 사항

### ISSUE THREAD

**Issue by hanabzu** [hanabzu/Warehouse-Management-System#2]
현재 작성된 Problem-Statement의 초안에 대해 수정할 부분에 대해서 의견 자유롭게 남겨주세요.

**Comment by ppikppik** [comment]
읽어봤는데, 상세하게 잘 써주셨네요! 우선은 정말 수고 많으셨고, 자동화 재고관리시스템 쪽으로 아이디어 추가한 부분도 괜찮은 거 같습니다!
다만, 시나리오를 읽어봤는데 prediction 내용이 빠져 있어서
창고 계정 쪽에 “Sales prediction” 항목을 통해 다음 달 물품의 판매 예측 리포트를 확인한다.
이런 식으로 한 줄 들어가면 좋을 것 같습니다!

**Comment by Gyong97** [comment]
- 시나리오 부분 점주파트에서
- "또한 "view stocks" 항목으로 현재 지점의 물품 재고 현황을 확인한다. " 이렇게 되어있는데 현재 지점이란 단어가 모호해서 연결된 창고의 물품 재고 현황 혹은 가까운 창고의 물품 재고 현황으로 고쳐도 좋을 것 같습니다.

**Comment by hanabzu** [comment]
@ppikppik 반영하였습니다.
@Gyong97  "View Stocks"는 로그인한 지점의 재고 상황을 보는 기능으로 생각했습니다.
그런데 생각해보니 현재 연결된 창고의 남은 물품 재고를 확인하는 기능도 확실히 "Transaction"에 명시해야 할 것 같네요. 반영하겠습니다.
