### ISSUE TITLE
논의 해보아야 할 점들을 Use-case에서 가져와 보았습니다.

### ISSUE THREAD

**Issue by Gyong97** [hanabzu/Warehouse-Management-System#24]
| 어드민 | 필요한 브랜드의 상품을 요청하거나 처리할 수 있다.   |                 | <- 어드민이 창고/점주에게 요청을 받은 브랜드를 해당 브랜드에게 신청하는 것이라고 이해했는데 이는 이 어플리케이션에서 필요한 기능은 아니라고 생각합니다. 

| 어드민 | 해당 브랜드에 상품에 대한 컴플레인 혹은 의견을 보냄 | SendComplaintoBrand | <- 마찬가지로 브랜드와 어드민 간의 소통이 이 어플리케이션에서 필요한 것인가? 에 대해 생각 필요

| 어드민 | 상품이 부족할 시 대체할 수 있게 창고를 확인 할 수 있다.     |                 | <-이해 어려움. 창고/지점에 상품이 부족? 자동 발주 기능을 위한 것인가요?

| 어드민 | 배송 상황을 확인 할 수 있다.     |                 | <- 배송 상황 확인이 필요한가? 에 대해 생각해 볼 필요가 있을 것 같아요.

| 창고 관리자 | 창고에 브랜드를 등록                               | AddBrand |  <- 상품 등록시 브랜드의 정보가 들어가면 브랜드 등록이 따로 필요한가? 에 대해 생각 필요

| 어드민 | 리포트를 통해 물품에 대한 구매량을 확인 할 수 있다        |                 | <- 어떤 물품 구매량인지 모르겠어요. 창고에 입고하는 걸 말하는 건가요?

| 창고 관리자 | 창고의 발주 내역 열람                                   | ViewTransactions | <-창고의 발주 내역이 점주가 신청한 발주인가요?

| 창고 관리자 | 연결된 브랜드 열람                               | ViewBrands | <- 연결된 브랜드가 무얼 의미하는 건가요? 어드민과 연결되어 상품 입고가 가능한 브랜드?

| 점주 | 판매 동향리포트 탭에서 리포트에 대한 피드백을 한다. ( REQ-15 기반 )       | FeedbackReports | <- 리포트에 대한 피드백이 어떤 것인지 잘 모르겠어요.

일단 보이는 부분에 대해서 적어 보았습니다. 해당 어플리케이션에 사용자가 원하는 기능이 맞는가에 대한 의문이 드는 것도 있고 다소 모호하게 적혀있어서 파악이 어려운 것도 적어 보았습니다.
 생각해보시고 필요 없는 기능인 것 같다. 혹은 더 필요한 기능인 것 같다. 라고 생각하는 부분들은 REQ 수정이 먼저 일 것 같아요.

**Comment by hanabzu** [comment]
브랜드<->어드민 사이의 커뮤니케이션은 필요없는 것이 맞는 것 같습니다. 작성자가 수정해주시기 바랍니다.

창고 관리자는 제가 작성하였는데 창고의 발주내역 열람-> 창고가 브랜드에게 자동으로 발주한 내용을 확인하는 것입니다.  그렇게 두고보니 창고관리자는 유저이므로 창고의 발주기능은 다른 부분에 전담하게끔 생각하였는데 생각해보면 자동으로 발주는 하지만 창고 관리자의 계정에서 발주하는 것은 맞으므로 창고 관리자의 use case로 추가해두는 것이 맞는것 같습니다. 수정하겠습니다.
브랜드 등록도 삭제하겠습니다. 대신 제공하는 상품 열람 기능에서는 브랜드별, 상품유형별 등으로 확인할 수 있게 하는 것이 좋을 것 같아요. 이부분은 req에서 NF를 추가하겠습니다.

**Comment by Gyong97** [comment]
배송 상황은 어떻게 생각하시나요?

**Comment by hanabzu** [comment]
배송상황도 일단 빼고 생각하는 것이 좋아보입니다.

**Comment by ppikppik** [comment]
저도 REQ의 내용을 반영하는 과정에서 조금 모호하다고 생각했는데 1.브랜드 <-> 어드민 사이의 커뮤니케이션과 2. 배송상황 내용부분을 삭제하고, REQ에서도 제거하도록 하겠습니다.
