### ISSUE TITLE
유저 모듈에 대해서

### ISSUE THREAD

**Issue by hanabzu** [hanabzu/Warehouse-Management-System#34]
유저 모듈에 대해서 얘기할 점에 대해 말씀드리겠습니다.

현재 유저 모듈은 신규 유저의 등록/삭제, 로그인, 회원정보 수정 등에 대해 관여하는데
관련된 유저의 정보는 데이터 모듈에 저장합니다.
그렇다면 유저 모듈의 존재가 굳이 필요없다고도 생각이 들 수 있습니다.
하지만 만약 유저들의 아이디/패스워드가 데이터로 그대로 저장된다면 만약 데이터 베이스가 유출되면 보안상에 문제가 있을 수 있습니다.
그러므로 유저 모듈의 존재는 로그인 기능이 데이터 모듈에 직접적인 접근을 하는 것을 막음과 동시에 유저정보를 저장하거나 매치 여부를 확인할 때 암호화를 통한 확인 작업을 하는 것이라고 생각합니다.
즉 예를 들어 회원가입을 하고 승인이 되었을 때 유저가 입력한 아이디와 패스워드 정보는 암호화되어 데이터 모듈로 전송되고 데이터 모듈은 암호화된 아이디/패스워드만 알고 원래 아이디/패스워드는 모르는 것으로 하는 것이 좋을 것 같습니다.
암호화된 텍스트를 푸는 키는 유저 모듈만 가지고 있는 것으로 하고요.
또 관련해서 로그인 성공/실패 내역도 데이터 베이스에 저장하면 좋을 것 같습니다. (더 추가한다면 연속 실패 시 일정 시간동안 로그인 불가능)

위의 내용은 REQ에 NF로 몇가지 정도 추가하면 될 것 같아요.
이에 관해 팀원들의 의견도 들어보고 싶습니다!

**Comment by Gyong97** [comment]
네. 괜찮은 것 같아요. 추가로 사용자가 기능들을 실행하기 위해서 적절한 권한을 가지고 있는 사용자인지 확인하는 것도 유저모듈의 일이라고 생각해요

**Comment by ppikppik** [comment]
저도 NF로 몇 가지 추가하면 좋을 것 같습니다!

**Comment by hanabzu** [comment]
네 제가 현재 로그인/로그아웃 use case 작성 중이니 유저 모듈 use case 담당자는 참고하여 작성해주세요.

**Comment by hanabzu** [comment]
추가로 REQ에 위의 내용들 NF로 추가하도록 하겠습니다.

**Comment by hanabzu** [comment]
+ 비슷한 구도로 Register에서 입력하는 계정 정보도 바로 데이터 모듈에 저장하지 않고 유저 모듈에서 임시 저장하고 있는 건 어떨까요 (암호화된 상태로)
일단 이렇게 작성하겠습니다

**Comment by ppikppik** [comment]
음 넵 저는 좋은 거 같습니다
