### ISSUE TITLE
창고/ 점주 계정 기능 추가 의견

### ISSUE THREAD

**Issue by Mesopotamia2957** [hanabzu/Warehouse-Management-System#4]
ADMIN쪽에서 view brands/products를 하기위해 창고나 점주계정쪽에서 brand/product에 대해 추가를 요청하는 기능도 있으면 좋을것 같다고 생각이 들었습니다. 

요약하자면 제품/브랜드에 대한 추가/삭제 요청또한 시스템상에서 이루어지면 좋을것 같습니다.

**Comment by hanabzu** [comment]
창고나 점주에서 특정 브랜드나 상품을 어드민에게 신청하면 어드민이 승인하여 해당 브랜드/상품을 매니지먼트에서 추가할 수 있도록 말이죠? 삭제 요청은 컴플레인 기능으로 대체하면 어떨까요? 지점이나 창고에서 컴플레인을 통해 어드민이 사안 확인 후 결정하는 것으로 하면 좋을 것 같습니다. 일단 요청기능, 컴플레인 기능으로 추가해둘테니 또 의견 부탁드립니다!
