### ISSUE TITLE
안녕하세요, 같은 분반 수업 듣는 Team 3 학생입니다.

### ISSUE THREAD

**Issue by d0lim** [hanabzu/Warehouse-Management-System#41]
안녕하세요, 프로젝트 진행하신다고 고생이 많으십니다.  
다름이 아니라, 저희 레포를 포크도 떠가시고 양식도 완전히 차용하셔서 사용하시던데  
참고 하시는건 괜찮지만 저희에게 일절 연락 한통 없으신 채로 완전히 베껴서 사용하신 것 같아서 기분이 묘하네요..  
Fork 해가셨다가 레포 지우신 것 까지 일단 모두 캡쳐 떠 두긴 했습니다.  
프로젝트 진행에 있어서 도움이 될 수 있었다는 점은 기분이 좋지만 참고하실거면 Github Issue를 통해서라도 한번 물어봐 주실 수 있었을 텐데 아쉽습니다.

**Comment by d0lim** [comment]
커밋 로그가 올라가는 것이 계속 보이는데, 20시까지 답변 안주시면 교수님께 질문차 메일 한번 드리도록 하겠습니다.  
@hanabzu @Mesopotamia2957 @ppikppik @boy-min @Gyong97 @mnyee

**Comment by hanabzu** [comment]
안녕하세요. Team 9 한경빈 학생입니다.
먼저 정말 죄송하다는 말씀 드립니다.
저를 포함한 저희 팀원분들 모두 깃 환경에 익숙하지 않은 지라 도큐먼트 작성 등에 있어서 여러 곳을 참고하였는데 그 과정에서 Fork하고 양식도 따라서 하게 된 것 같습니다.
이 부분에 있어서는 변명의 여지가 없습니다. 학교 과제이기도 하므로 정말 죄송할 따름입니다.
이에 대해서는 제가 팀원분들께 팀 대표로 메일로 사과드리겠습니다. 
지금 작성 중인 문서의 양식에서 베껴온 것으로 보이는 문서는 모두 폐기하고 내용을 옮기도록 하겠습니다.
다시 한번 정말 죄송합니다. 메일 드리겠습니다.

**Comment by d0lim** [comment]
네, 알겠습니다.
