### ISSUE TITLE
AuthenticateUser 관련

### ISSUE THREAD

**Issue by hanabzu** [hanabzu/Warehouse-Management-System#53]
저희 login, logout, register에서 AuthenticateUser를 inlcude하는데 지금 login에서 새로 이 작업을 하는 부분을 추가하는 것보단 authenticateUser를 사용해서 판별하는 것이 좋지않을까요?
제가 지금 authenticateUser를 작성 중인데 user module에게서 accountInfo ( ID, password, time)을 받아서 db에 있는지 검사하고, 만약 아이디가 같은 계정이 있다면 여기서 또 두가지로 패스워드까지 같은 경우, 패스워드가 다른 경우 ( 잘못된 로그인 시도), 또 아이디가 없는 경우 (역시 잘못된 로그인 시도 혹은 새로운 계정생성), 이렇게 총 세 경우에 대한 return값을 user module에게 주는 것으로 생각 중입니다. (이 과정에서 로그인 시도의 경우 userData를 include하여 저장하도록 함)
register 부분은 좀 변경이 불가피할듯 한데 먼저 authenticateUser 계속 고쳐볼테니 혹시 영준님 생각과 다른 부분이 있거나 바꿔야할 부분이 있다면 말해주세요.

**Comment by ppikppik** [comment]
네 저도 authenticateUser를 사용해서 판별하는 것이  좋을 것 같습니다.
그점 참고해서 문서 작성하도록 하겠습니다.
