### ISSUE TITLE
Requirements 작성 시 통일해야 할 점

### ISSUE THREAD

**Issue by hanabzu** [hanabzu/Warehouse-Management-System#7]
현재 파트를 나눠서 작성하는 Requirements에서 사용자들의 명칭 등을 통일하면 좋겠습니다.

-사용자의 명칭-
어드민 (전체 시스템 관리자)
창고 관리자 (각 창고의 관리자)
점주 (각 지점의 관리자)

위와 같이 통일해주시고 그 외에 필요한 통일 사항은 이 이슈에 남겨주세요.

**Comment by ppikppik** [comment]
넵 그게 좋을 것 같습니다!
